version: 2.1
workflows: 
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: daksh-kotian/dk
    steps: 
      - run: open -a firefox https://circleci.com/enterprise